game_inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_item, show_html, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, add_item, decrease_item, remove_item, get_item_json, add_item_ajax, create_item_flutter

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('html/', show_html, name='show_html'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('add_item/<int:id>', add_item, name='add_item'),
    path('decrease_item/<int:id>', decrease_item, name='decrease_item'),
    path('remove_item/<int:id>', remove_item, name='remove_item'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-ajax/', add_item_ajax, name='add_item_ajax'),
    path('create-flutter/', create_item_flutter, name='create_item_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    amount = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "amount", "description"]

main/views.py
import datetime
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from main.forms import ItemForm
from main.models import Item
from django.urls import reverse
from django.core import serializers
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
import json

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user=request.user)
    item_counter = items.count()
    item_sum = sum([item.amount for item in items])
    context = {
        'nama': request.user.username,
        'kelas': 'PBP D',
        'item_sum': item_sum,
        'item_counter': item_counter,
        'items': items,
        'last_login': request.COOKIES['last_login'],
        #'name': 'The Art of War',
        #'amount': 1,
        #'description': 'The ancient Chinese military text, dating from the Late Spring and Autumn Period, was written by Sun Tzu.',
    }

    return render(request, "main.html", context)

@login_required(login_url='/login')
def add_item(request, id):
    try:
        data = Item.objects.filter(user=request.user).filter(pk=id).first()
        data.amount += 1
        data.save()
    finally:
        return HttpResponse(status=200)

@login_required(login_url='/login')
def decrease_item(request, id):
    try:
        data = Item.objects.filter(user=request.user).filter(pk=id).first()
        data.amount -= 1
        if data.amount <= 0:
            data.delete()
            return HttpResponse(status=200)
        data.save()
    finally:
        return HttpResponse(status=200)

@login_required(login_url='/login')
@csrf_exempt
def remove_item(request, id):
    try:
        data = Item.objects.filter(user=request.user).filter(pk=id).first()
        data.delete()
    finally:
        return HttpResponse(status=204)

def get_item_json(request):
    artifact_item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', artifact_item))
    
@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        amount = request.POST.get("amount")
        description = request.POST.get("description")
        user = request.user

        new_item = Item(name=name, amount=amount, description=description, user=user)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)
    
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_item.html", context)



def show_html(request):
    items = Item.objects.all()
    item_counter = items.count()
    item_sum = sum([item.amount for item in items])
    context = {
        'item_counter': item_counter,
        'item_sum': item_sum,
        'items': items,
    }
    return render(request, "show_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")
    
def show_json(request):
    data = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")
    
def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")
    
def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_item = Item.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["description"]
        )

        new_item.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %} 

{% block content %}
<div class = "container mt-5">
	<div class="card">
		<div class="card-header">
			<h1 class="text-left">Add New Item</h1>
		</div>
		<div class="card-body">
			<main class="form-signin w-100 m-auto">
				<form method="POST">
					{% csrf_token %}
					<table class="table">
						{{ form.as_table }}
						<tr>
							<td></td>
							<td>
								<div class="text-left">
									<button class="btn btn-primary" type="submit">Add Item</button>
								</div>
							</td>
						</tr>
					</table>
				</form>
			</main>
		</div>
	</div>
</div>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Sign In</title>
{% endblock meta %}

{% block content %}

<div class = "container mt-5">
	<div class="row">
        <div class="col-md-6">
			<div class="card">
                <div class="card-header">
					<h1 class="text-left">Login</h1>
				</div>
				<div class="card-body">
					<main class="form-signin w-100 m-auto">
						<form method="POST" action="">
							{% csrf_token %}
							<table class="table">
								<div class="form-floating">
									<input type="text" name="username" class="form-control" id="floatingInput" placeholder="Username">
									<label for="floatingInput">Username</label>
								</div>
								<div class="form-floating">
									<input type="password" name="password" class="form-control" id="floatingInput" placeholder="Password">
									<label for="floatingInput">Password</label>
								</div>
								<div class="text-left">
									<button class="btn btn-primary" type="submit">Login</button>
								</div>
							</table>
						</form>
					</main>

					{% if messages %}
						<div class="alert alert-danger mt-3">
							<ul>
								{% for message in messages %}
									<li>{{ message }}</li>
								{% endfor %}
							</ul>
						</div>
					{% endif %}
					
					Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a>
				</div>
			</div>
		</div>
		<div class="col-md-6"></div>
	</div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
	<nav class="navbar navbar-expand-lg bg-body-tertiary rounded">
		<div class="container-fluid">
			<div class="collapse navbar-collapse d-lg-flex" id="header">
				<a class="navbar-brand col-lg-3 me-0" href="#">Artifact Game Inventory</a>
				<ul class="navbar-nav col-lg-6 justify-content-lg-center">
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="#">{{ nama }}</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'main:create_item' %}">Add Item</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Artifact by AJAX</a>
					</li>
				</ul>
				<div class="d-lg-flex col-lg-3 justify-content-lg-end">
					<a class="nav-link" href="{% url 'main:logout' %}" <button class="btn btn-primary">Logout</button></a>
				</div>
			</div>
		</div>
    </nav>
	
	<div class = "container mt-5">
		<div class="card">
			<div class="card-body">
				<h1>Artifact List</h1>
				<p>Username : {{ nama }}</p>
				<p>Last login: {{ last_login }}</p>
				<p>Kelas : {{ kelas }}</p>
				<p id="counter_item">Ada {{ item_counter }} jenis item dalam inventory</p>
				<p id="counter_total">Ada total {{ item_sum }} item dalam inventory</p>
			</div>
		</div>
	</div>
	
	<div class="container mt-5">
		<div class="row" id="daftar_item">
		</div>
	</div>
	
	<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					<form id="form" onsubmit="return false;">
						{% csrf_token %}
						<div class="mb-3">
							<label for="name" class="col-form-label">Name:</label>
							<input type="text" class="form-control" id="name" name="name"></input>
						</div>
						<div class="mb-3">
							<label for="amount" class="col-form-label">Amount:</label>
							<input type="number" class="form-control" id="amount" name="amount"></input>
						</div>
						<div class="mb-3">
							<label for="description" class="col-form-label">Description:</label>
							<textarea class="form-control" id="description" name="description"></textarea>
						</div>
					</form>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
					<button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
				</div>
			</div>
		</div>
	</div>

<script>
    async function getItem() {
        return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
    }
	async function refreshItem() {
        document.getElementById("daftar_item").innerHTML = ""
		document.getElementById("counter_item").innerHTML = ""
		document.getElementById("counter_total").innerHTML = ""
        const items = await getItem()
        let htmlString = ``
		let count = 0
		let sum = 0
        items.forEach((item, index) => {
            htmlString += `<div class="col-lg-4 mb-4">
				<div class="card" ${index == items.length - 1 ? 'style="color: gold;"' : ''}>
					<div class="card-body">
						<h3 class="card-title">${item.fields.name}<h3>
						<p class="card-text">Amount : ${item.fields.amount}</p>
						<p class="card-text">Description : ${item.fields.description}</p>
					</div>
					<div class="btn-group">
						<a class="btn btn-primary" onclick="addOneItem(${item.pk})">+</a>
						<a class="btn btn-primary" onclick="decreaseItem(${item.pk})">-</a>
						<a class="btn btn-danger" onclick="deleteItem(${item.pk})">Remove</a>
					</div>
				</div>
			</div>`
			count += 1
			sum += item.fields.amount
        })
        
        document.getElementById("daftar_item").innerHTML = htmlString
		document.getElementById("counter_item").innerHTML = `Ada ${count} jenis item dalam inventory`
		document.getElementById("counter_total").innerHTML = `Ada total ${sum} item dalam inventory`
    }

    refreshItem()
	
	function addItem() {
        fetch("{% url 'main:add_item_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshItem)

        document.getElementById("form").reset()
        return false
    }
	
	document.getElementById("button_add").onclick = addItem
	
	function deleteItem(itemId) {
		fetch(("/remove_item/" + itemId), {
            method: "DELETE"
        }).then(refreshItem)
		return false
	}
	
	function addOneItem(itemId) {
		fetch(("/add_item/" + itemId), {
            method: "GET"
        }).then(refreshItem)
		return false
	}
	
	function decreaseItem(itemId) {
		fetch(("/decrease_item/" + itemId), {
            method: "GET"
        }).then(refreshItem)
		return false
	}
	
</script>
{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class = "container mt-5">
	<div class="row">
		<div class="card">
			<div class="card-header">
				<h1 class="text-left">Register</h1>
			</div>
		<div class="card-body">
			<main class="form-signin w-100 m-auto">
				<form method="POST" >  
					{% csrf_token %}  
					<table class="table">
						{{ form.as_table }}  
						<tr>  
							<td></td>
							<td>
								<div class="text-left">
									<button class="btn btn-primary" type="submit">Daftar</button>
								</div>
							</td>  
						</tr>  
					</table>  
				</form>
			</main>

			{% if messages %}
				<div class="alert alert-danger mt-3">
					<ul>   
						{% for message in messages %}  
							<li>{{ message }}</li>  
							{% endfor %}  
					</ul>
				</div>
			{% endif %}
			</div>
		</div>
	</div>
</div>  

{% endblock content %}

main/templates/show_item.html
{% extends 'base.html' %} 

{% block content %}

	<p>Ada {{ item_counter }} jenis item pada aplikasi ini</p>
	
	<p>Ada total {{ item_sum }} item pada aplikasi ini</p>
	
	<table>
		<tr>
			<th>No</th>
			<th>Name</th>
			<th>Amount</th>
			<th>Description</th>
		</tr>

		{% for item in items %}
			<tr>
				<td>{{forloop.counter}}.</td>
				<td>{{item.name}}</td>
				<td>{{item.amount}}</td>
				<td>{{item.description}}</td>
			</tr>
		{% endfor %}
	</table>

{% endblock %}